version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgresql+psycopg2://avnadmin:AVNS_8YZJQ2WxUzOLlaDLCfg@pg-ca14958-michalek32001-bf66.l.aivencloud.com:22974/defaultdb?sslmode=require
    volumes:
      - .:/app
